# Defaults
defaults:
  - _self_
  - dset: musdb18hq
  - optim: optim_sep
  - scheduler: step
  - src_mod@stft_model: bsrnn
  - src_mod@phase_model: phaseprior
  - src_mod@spectro_model: umx
  - spec_inv: default
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

# Targets to separate
targets:
  - vocals
  - bass
  - drums
  - other

# Separator type and parameters
separator: deephr

# General parameters
seed: 42
eps: 1e-7
out_dir: outputs/
data_dir: data/musdb18hq/

# Audio / STFT
sample_rate: 44100
#n_fft: 2048
#n_hop: 512
n_fft: 4096
n_hop: 1024

# Evaluation parameters
parallel_cpu: true
eval_device: cuda
eval_segment_len: 10.0
eval_overlap: 0.1
eval_max_len:
verbose_per_track: True
sdr_type: global
win_dur: 1.0 # for the museval SDR
only_append_res: False

# Booleans
fast_tr: False
resume_tr: False
load_pretrained_sources: True

# By default, no prior ckpt path for the TB logs
ckpt_path_log:

# Hydra-related
hydra:  
  output_subdir: null  
  run:  
    dir: .