cfg_optim:
  max_epochs: 100
  patience: 10
  lr: 0.001
  grad_clip_norm: 5
  loss_type: L1
  loss_domain: t
cfg_scheduler:
  name: step
  gamma: 0.98
  step_size: 2
targets: vocals
sample_rate: 44100
n_fft: 2048
n_hop: 512
eval_segment_len: 10.0
eval_overlap: 0.1
sdr_type: global
win_dur: 1.0
verbose_per_track: true
eval_device: cuda
rec_dir: null
eps: 1.0e-07
module_type: time
target: vocals
feature_dim: 64
num_repeat: 8
name: bsrnn
out_dir: outputs/
