#!/bin/bash
CLUSTER=${1:-"graffiti"}

oarsub -vv -l /nodes=1,walltime=48 -p $CLUSTER -q production jobs/train.sh --array-param-file jobs/params_train.txt
#oarsub -vv -l /nodes=1,walltime=48 -p $CLUSTER -q production jobs/train.sh --array-param-file jobs/params_bscnn.txt  # for BSCNN
