#!/bin/bash
#CLUSTER=${1:-"graffiti"}
#CLUSTER=${1:-"grue"}
CLUSTER=${1:-"gruss"}
#CLUSTER=${1:-"grele"}

oarsub -vv -l /nodes=1,walltime=24 -p $CLUSTER -q production jobs/train.sh --array-param-file jobs/params_train.txt