#!/bin/sh

JOBTYPE=${1:-"train"}
CLUSTER=${2:-"grele"}
PARAMARRAY=${3:-"variants"}

if [[ $JOBTYPE == "train" ]]
then
	full_command="oarsub -vv -l /nodes=1,walltime=48 -p $CLUSTER -q production jobs/train.sh --array-param-file jobs/params/${PARAMARRAY}.txt"
elif [[ $JOBTYPE == "test" ]]
then
	full_command="oarsub -vv -l /gpu=1,walltime=12 -p $CLUSTER -q production jobs/test.sh --array-param-file jobs/params/test.txt"
fi

$full_command
