#!/bin/sh

if [ $1 == "cpu" ]
then
	full_command="oarsub -vv -l /nodes=1,walltime=3 -p grvingt -q production -I"
elif [ $1 == "graffiti" ] || [ $1 == "grue" ] || [ $1 == "grele" ] || [ $1 == "gruss" ] || [ $1 == "gres" ]
then
	full_command="oarsub -v -l nodes=1,walltime=3 -p $1 -q production -I"
elif [ $1 == "graffiti-13" ]
then
	full_command="oarsub -v -l nodes=1,walltime=6 -p $1 -q production -I"
else
	full_command="oarsub -v -l gpu=1,walltime=3 -q production -I"
fi

echo $full_command

read -p "Continue and launch this command? (y/n)" 

case $REPLY in 
	[Yy]* ) 
	echo "Command launched"
	$full_command
	;;
	"" )
	echo "Command launched"
	$full_command
	;;

	* ) 
	echo "Aborted"
	exit
	;;
esac
