# General
max_epochs: 200
deterministic: False

# Algo-related
algo: adam
lr: 0.001
grad_clip_norm: 5

# Loss
loss_type: L1
loss_domain: t+tf
monitor_val: sdr # either "loss" or "sdr"

# Early stopping
patience: 10

# Multi GPU parameters
ngpus:  # leave None for using all available GPUs
sync_bn: True
acc_grad: 1