# Evaluation-related parameters (val and test)
device: cuda
segment_len: 10.0
overlap: 0.1
hop_size: # leave it to None for using the linear fader; if a value is specified, it will use the OLA version
verbose_per_track: True
sdr_type: global # 'global' or 'museval' (so-called uSDR or cSDR)
win_dur: 1.0 # used for the museval SDR
rec_dir: