name: phaseprior
target: vocals
sample_rate: ${sample_rate}
n_fft: ${n_fft}
n_hop: ${n_hop}
out_dir: ${out_dir}
# Model parameters
hidden_size: 256
num_conv_blocks: 6
cutoff_freq_band: 128

# Training-related
lr: 0.001
grad_clip_norm: 1
loss_type: L1
loss_domain: t