name: umx
target: vocals
sample_rate: ${sample_rate}
n_fft: ${n_fft}
n_hop: ${n_hop}
out_dir: ${out_dir}

# Model parameters
hidden_size: 1024
bandwidth: 16000
nb_layers: 3
nb_channels: 2
unidirectional: False

# Training-related
lr: 0.0001
grad_clip_norm: 0
loss_type: L1 # essayer aussi de finir training avec MSE ?
loss_domain: mag